### ISSUE TITLE
Infografia 

### ISSUE THREAD

**Issue by CarlosSD16** [SistemasTecTlaxiaco/infografia-CarlosSD16-1#2]
[infografia_JuanCarlos.pdf](https://github.com/SistemasTecTlaxiaco/infografia-CarlosSD16-1/files/7117556/infografia_JuanCarlos.pdf)

**Comment by garaudy12** [comment]
Agrupa los elementos de manera correcta, las imágenes están de acorde al texto, cumple con las cinco fuentes de información requeridas.
Calificación: 20 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado
